### ISSUE TITLE
Roadmap for V2.0

### ISSUE THREAD

**Issue by nihgwu** [Autodesk/react-base-table#3]
Here is the wishlist I'd like to have for the next major version:

* [ ] Replace `react-virtualized` with `react-window`
* [ ] Dynamic row heights, depends on https://github.com/bvaughn/react-window/pull/102
* [ ] Make virtualization configurable
* [ ] A11y
* [ ] UT

**Comment by Gervwyk** [comment]
Hi @nihgwu ! I'm liking BaseTable so far! However it will only be useful for me if we have dynamic row heights. Where can I start to make this happen? I see it's dependant on #102, but it looks like that can still be a while.

**Comment by nihgwu** [comment]
I'm sorry  @Gervwyk I'd say I won't start working on that until that PR is merged, I'm lot expert on this field, do you have any other ideas?

**Comment by Gervwyk** [comment]
No me neither. Just started looking at some of the code, do you think it would be possible to just achieve this via [CellMeasurer](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md)? Similar to the way it's done in react-virtualized?

**Comment by nihgwu** [comment]
I think `CellMeasurer` is too heavy, that's why I didn't support that when `BaseTable` is built on `react-virtualized`

**Comment by zmitry** [comment]
What do you thing about configuring react-draggable and make it lazy loadable ?

**Comment by nihgwu** [comment]
@zmitry any concern about that? I do have the plan to remove the dependency on `react-draggable`

**Comment by zmitry** [comment]
@nihgwu it's used only for column resizer so it might be useless for some cases where you don't need that feature. I don't mind to have it as dependency but it takes 1/3 of the table bundlesize, so it might be quire useful to be able to import it lazily only if you use it. If you want to remove that will solve my usecase also.

**Comment by Nokecy** [comment]
大佬 打算什么时候出新版本啊~~~~~

**Comment by nihgwu** [comment]
@Nokecy I don't see any MUST to bump the major version soon, until the dynamic row height dependency is resolved

**Comment by elevator3** [comment]
First of all I just wanted to say that I really really like the react-base-table but am unable to use it right now for the following reasons. It also seems to me that those are issues that everyone will benefit from…

- Lack of documentation. The examples are great but they do not describe well what are the additional options or full usage of the particular feature. Not as easy to figure whatever you are looking at especially for the more complicated examples.

- I am not sure who is using the ellipsis in the cells and why would that be a default other than the table not being able to support auto row heights.

- If you use the rowHeight to modify the row height of the whole table the performance when displaying hundreds of rows, which is something that is supposed to be better, goes out of the window.


Please understand this is not a criticism of what you currently have but a request to make it easier for people to understand and start use it with enough basic features out of the box.

**Comment by nihgwu** [comment]
> Lack of documentation. The examples are great but they do not describe well what are the additional options or full usage of the particular feature. Not as easy to figure whatever you are looking at especially for the more complicated examples.

I definitely agree with you that documentation is important for a component and BaseTable is really bad on that, I'll try my best to add more in the future

> I am not sure who is using the ellipsis in the cells and why would that be a default other than the table not being able to support auto row heights.

I don't make something like `EllipsisText` as default to make BaseTable irrelevant to any ui libraries, so you are free to choose the component with the style aligned to your application, you can use [react-texty](https://github.com/nihgwu/react-texty) or other components as your wish, you just need to customize the `TableCell` via `components` https://autodesk.github.io/react-base-table/examples/tooltip-cell

> If you use the rowHeight to modify the row height of the whole table the performance when displaying hundreds of rows, which is something that is supposed to be better, goes out of the window.

Sorry I don't understand your statement here

**Comment by nihgwu** [comment]
@elevator3 Sorry for the late response, I missed your reply somehow, for your first point, I'd internally more then 90% of our teams/products are using  fixed row height, I do want to support dynamic row height which automatically stretch/shrink on the cell's content, it's the 4th item in the roadmap, the feature in `react-window` is still experimental, and still not available in any stable release, I know I can use the same strategy as `react-virtualized` does using CellMeasurer, but it's too heavy and I don't want to use. Maybe I will make is available in `virtualized=false` mode, which is the 5th item in the roadmap.

For the second, I don't see any difference by switching the the rowHeight between 130 and the default value, why `rowHeight={130}` performed bad?

**Comment by gyurcigyurma** [comment]
My wish (or maybe already exists?) that if XHR response has no exact "children" key, then I don't have to transform it.  My problem that I call a public API, which sends a tree-structure and the master key is "details" which is a collection.  So I just rename all "details" to "children". 
So expecting like this:
```
              <BaseTable
                  width={width}
                  height={height}
                  columns={tableColumns}
                  data={dataToRender}
                  expandColumnKey='code'
                  **childrenAccessorKey="details"**
                  rowHeight={40}
                />
```
Sorry maybe this is an existing feature but I couldn't find.

**Comment by nihgwu** [comment]
@gyurcigyurma that's not on the list, will add it, thanks

**Comment by bammoo** [comment]
Why not use react-window's VariableSizeGrid to solve Dynamic row heights?

**Comment by jamesonhill** [comment]
Is there a WIP for this? I'm forking this project to add dynamic row height support for a project i'm working on. If I can add that support in a matter consistent w/ the v2 api, I would prefer to do so.

**Comment by nihgwu** [comment]
@jamesonhill sorry I'm a bit busy those days, will start the work next month, the challenge to add dynamic row height support in master(v1) is that we are calculating the total height to support infinite loading, we should use another mechanism in the next version

**Comment by jamesonhill** [comment]
@nihgwu Sounds good. I will make an attempt at dynamic row heights in our fork. If we can get it working I'm happy to help w/ v2 once you have the time to begin it.

**Comment by jamesonhill** [comment]
@nihgwu Is it worthwhile for me to open a PR adding Typescript type declarations? If you'd rather wait until V2, I can add them to @DefinitelyTyped instead for V1.

**Comment by nihgwu** [comment]
@jamesonhill I'm not ready to add type declarations in V1 as I have little knowledge on TS right now, and I'm not going to add something I'm not familiar with, sorry. So I'd prefer to add them to DefinitelyTyped for now

**Comment by nihgwu** [comment]
Hey @jamesonhill are you still interested in the TS type declarations, I'm going to do it in V1, and based on @sskiswani 's work in #93, I'm pretty new to TS, so if you can help to make it better that would wonderful
BTW, does the dynamic row height work well in your apps?

**Comment by jamesonhill** [comment]
@nihgwu yes i can help w/ the TS types & conversion. I didn't get around to submitting a PR to @DefinitelyTyped, but I have a good start on them in our repo that I can bring over. So far so good w/ dynamic row heights. I've implemented it on one of our more basic grids (only displays & sorts data, no frozen cols or anything fancy) and it works well. Working on a more complex instance w/ resizing & freeze currently.

**Comment by nihgwu** [comment]
cool, I just release a new version v1.10.5 within #192 which I think should be the last part for the dynamic row height feature

**Comment by jamesonhill** [comment]
I'll open a WIP PR later today w/ the start of the typings for V1.

**Comment by abubakir1997** [comment]
Any plans on including grouping by one or more columns? Just like in material table https://material-table.com/#/docs/features/grouping

**Comment by nihgwu** [comment]
@abubakir1997 it won't be a builtin feature, you can implement it by yourself like this https://autodesk.github.io/react-base-table/examples/multi-header

**Comment by jamesonhill** [comment]
For V2, would you consider making the params for `unflatten` and `flattenOnKeys` an object? Since there are multiple default params, it makes it kinda awkward IMO to only pass single param.

For example, with `unflatten(array, rootId = null, dataKey = 'id', parentKey = 'parentId')`, if I want to just provide a custom `parentId` I would have to do `unflatten(array, undefined, undefined, myParentId)`. 

It would be nicer DX IMO if I could do something like `unflatten(array, { parentId: someOtherId })`.

**Comment by nihgwu** [comment]
@jamesonhill good idea

**Comment by gjthompson1** [comment]
I'm not sure if this has come up before. But the package doesn't really handle a large number of columns well. Or maybe I am doing something wrong....? 

If you play around with [this](https://bvaughn.github.io/react-virtualized/#/components/Grid) you can see that with 1,000  columns it performs well but with base table just cranking the number of columns up to 1,000 here https://autodesk.github.io/react-base-table/playground scrolling down becomes very clunky.

**Comment by jamesonhill** [comment]
@gjthompson1 `react-virtualized` supports horizontal virtualization, while this one does not. Doesn't seem like an apples to apples comparison.

**Comment by nihgwu** [comment]
@gjthompson1 This is my thoughts on this kind of questions https://github.com/Autodesk/react-base-table/issues/36#issuecomment-668587991, and there is a workaround actually https://github.com/Autodesk/react-base-table/issues/36#issuecomment-670474299, you will find it works well with 1000 columns

**Comment by gjthompson1** [comment]
@nihgwu very nice, yeh that seems to be much smoother. Thank you!

**Comment by dpyzo0o** [comment]
Hi, @nihgwu , really nice work for the library.  When do we expect to have the v2 released? This roadmap has been open for 2 years.

**Comment by kaleem-elahi** [comment]
Many wonderful feature, I don't know why but table has some issues, It works in Mobile but not showing up in desktop 

great work @nihgwu

**Comment by kaleem-elahi** [comment]
Need this  version 2 release

**Comment by nihgwu** [comment]
It has been more than two years since I created this ticket, a lot of things have changed, for example I'm not the admin of this repo anymore, so I can't land any changes(I revoked my 2FA to Github, I emailed to opensource@autodesk.com for the permission but no response for quite a long time). Although I don't work for the project which I created this component for, but I always have the willing to make the wish-list come true. Thanks for the abandonment of IE(the only reason I used three tables to achieve frozen columns), those features could be accomplished in a super simple way and much better performance(using `position: sticky`, and also unblocks a lot of wonderful features which are hard to implement before, like sticky header on window scrolling, I made a simple demo from scratch, but it's more a toy in my spare time
![bs2](https://user-images.githubusercontent.com/2595058/128647545-f0c5242c-1b51-4c39-bc7f-cec70edfefb0.gif)

**Comment by kaleem-elahi** [comment]
Sorry if you mind, Does that mean we should not rely on this library more? @nihgwu

**Comment by nihgwu** [comment]
@kaleem-elahi No, even I don't use this component much as I leave the previous project, but it's a baby of mine, so I will keep on improving it(and it's still heavily used in the projects I worked on), and actually there are not much blocking issues for the current version, and I'll ask for the permission to access this repo for better maintenance, what I wanted to say is that for the next major version it's going to be a completely rewrite so it won't arrive soon

**Comment by nihgwu** [comment]
@jamesonhill not yet, I'll contact my ex-colleague for help, seems the open-source email address is abandoned

**Comment by fgatti675** [comment]
Hi everyone, how about just forking the project and creating a new package?

**Comment by bjoe87** [comment]
Hey @nihgwu was curious if getting rid of the multiple grids for frozen columns would be in this roadmap? I started looking into it and have it working but some of the snapshots need to be updated. Also is this still your vision for 2.0 or have new features come into mind since its been awhile? Thanks for the awesome grid btw! :)

**Comment by phaweens** [comment]
Hi @nihgwu, I'm trying your base-table out. Could you please add example for column grouping because it's essential for my work, thanks.
